# Generated by Django 5.1.2 on 2024-10-31 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Изображение')),
                ('population', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Популяция')),
                ('territory', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Территория')),
                ('continent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Континент')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guest Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('number_of_guests', models.PositiveSmallIntegerField(choices=[(1, '1 Guest'), (2, '2 Guests'), (3, '3 Guests')], verbose_name='Number of Guests')),
                ('check_in_date', models.DateField(verbose_name='Check-in Date')),
                ('destination', models.CharField(choices=[('italy, roma', 'Italy, Roma'), ('france, paris', 'France, Paris'), ('england, london', 'England, London'), ('switzerland, lausanne', 'Switzerland, Lausanne')], max_length=50, verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dop_photo', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Доп. фото',
                'verbose_name_plural': 'Доп. фотки',
                'db_table': 'photos',
            },
        ),
    ]
