# Generated by Django 5.1.2 on 2024-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guest Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('number_of_guests', models.PositiveSmallIntegerField(choices=[(1, '1 Guest'), (2, '2 Guests'), (3, '3 Guests')], verbose_name='Number of Guests')),
                ('check_in_date', models.DateField(verbose_name='Check-in Date')),
                ('destination', models.CharField(choices=[('italy, roma', 'Italy, Roma'), ('france, paris', 'France, Paris'), ('england, london', 'England, London'), ('switzerland, lausanne', 'Switzerland, Lausanne')], max_length=50, verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
